package jiya.learning.quizzify

data class Questionslist (
    var quizid: String? = null,
    var Quizgenre: String? = null,
    var QuestionNum1: String? = null,
    var Question1: String? = null,
    var optionA1: String? = null,
    var optionB1: String? = null,
    var optionC1: String? = null,
    var optionD1: String? = null,
   var co1: String? = null,

    var QuestionNum2: String? = null,
    var Question2: String? = null,
    var optionA2: String? = null,
    var optionB2: String? = null,
    var optionC2: String? = null,
    var optionD2: String? = null,
   var co2: String? = null,

    var QuestionNum3: String? = null,
    var Question3: String? = null,
    var optionA3: String? = null,
    var optionB3: String? = null,
    var optionC3: String? = null,
    var optionD3: String? = null,
   var co3: String? = null,

    var QuestionNum4: String? = null,
    var Question4: String? = null,
    var optionA4: String? = null,
    var optionB4: String? = null,
    var optionC4: String? = null,
    var optionD4: String? = null,
    var co4: String? = null,

    var QuestionNum5: String? = null,
    var Question5: String? = null,
    var optionA5: String? = null,
    var optionB5: String? = null,
    var optionC5: String? = null,
    var optionD5: String? = null,
   var co5: String? = null,

    var QuestionNum6: String? = null,
    var Question6: String? = null,
    var optionA6: String? = null,
    var optionB6: String? = null,
    var optionC6: String? = null,
    var optionD6: String? = null,
  var co6: String? = null,

    var QuestionNum7: String? = null,
    var Question7: String? = null,
    var optionA7: String? = null,
    var optionB7: String? = null,
    var optionC7: String? = null,
    var optionD7: String? = null,
   var co7: String? = null,

    var QuestionNum8: String? = null,
    var Question8: String? = null,
    var optionA8: String? = null,
    var optionB8: String? = null,
    var optionC8: String? = null,
    var optionD8: String? = null,
  var co8: String? = null,

    var QuestionNum9: String? = null,
    var Question9: String? = null,
    var optionA9: String? = null,
    var optionB9: String? = null,
    var optionC9: String? = null,
    var optionD9: String? = null,
    var co9: String? = null,

    var QuestionNum10: String? = null,
    var Question10: String? = null,
    var optionA10: String? = null,
    var optionB10: String? = null,
    var optionC10: String? = null,
    var optionD10: String? = null,
   var co10: String? = null

    )